language: java

jdk:
- oraclejdk8

sudo: required

services:
  - docker

before_install:
- docker pull fjgutierrezs91/mysql
- docker run --name mysql -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=example -e MYSQL_USER=web -e MYSQL_PASSWORD=123456 -p 33060:3306 -d mysql:latest
- docker ps -a

script: mvn clean verify
install: true
