language: java


jdk:
- oraclejdk8

sudo: required

services:
  - docker

before_install:
- docker pull fjgutierrezs91/mysql
- docker run --name web -p 8080:8080 --link mysql -d web
- docker ps -a

script: mvn clean verify
install: true
