server:
  port: 8080

spring:

  thymeleaf:
    cache: false
    encoding: UTF-8

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/VideoClub
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
