server: 
  port: 8080
  
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    content-type: text/html; charset=utf-8

security:
  headers:
    content-type: true
    content-security-policy-mode: report-only
    content-security-policy: "sniff"